apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-scale-job
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mongoDB.labels.app }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    checksum/replicas: "{{ .Values.mongoDB.replicas | quote | sha256sum }}"
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.jobs.scale.containersName }}
        image: {{ .Values.mongoDB.containers.image }}:{{ .Values.mongoDB.containers.tag }}
        {{- if .Values.jobs.scale.command }}
        command: {{ .Values.jobs.scale.command | toYaml | nindent 10 }}
        {{- end }}
        env:
        - name: HOME
          value: "/tmp"

        volumeMounts:
        - name: {{ .Values.jobs.scale.volumeMounts.name }}
          mountPath: {{ .Values.jobs.scale.volumeMounts.mountPath }}
          subPath: {{ .Values.jobs.scale.volumeMounts.subPath }}
      restartPolicy: {{ .Values.jobs.scale.restartPolicy }}
      volumes:
      - name: {{ .Values.jobs.scale.volumeMounts.name }}
        configMap:
          name: {{ .Release.Name }}-scale-job-config
