apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mongoDB.labels.app }}
data:
  mongodb.conf: |
    {{ .Values.mongoDB.config.mongodbConfig | nindent 4 }}
