apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mongoDB.labels.app }}
type: {{ .Values.mongoDB.secret.type }}
data:
  mongo-root-username: {{ .Values.mongoDB.secret.data.mongoRootUsername }}
  mongo-root-password: {{ .Values.mongoDB.secret.data.mongoRootPassword }}
  mongo-database: {{ .Values.mongoDB.secret.data.mongoDatabase }}
  mongo-username: {{ .Values.mongoDB.secret.data.mongoUsername }}
  mongo-password: {{ .Values.mongoDB.secret.data.mongoPassword }}
